-- Parâmetros de edição IA (ElevenLabs + mix trilha)
ALTER TABLE "vinheta" ADD COLUMN IF NOT EXISTS "ia_bed_volume" DOUBLE PRECISION NOT NULL DEFAULT 0.18;
ALTER TABLE "vinheta" ADD COLUMN IF NOT EXISTS "ia_voice_speed" DOUBLE PRECISION NOT NULL DEFAULT 1.0;
ALTER TABLE "vinheta" ADD COLUMN IF NOT EXISTS "ia_voice_stability" DOUBLE PRECISION NOT NULL DEFAULT 0.45;
